$ANSIBLE_VAULT;1.1;AES256
66363031363063323535383732366135353137333039363265376630656532626664653537366230
6364626535643030663665376334666462386533646663660a663166653034623439303232626333
31613634393139646430643663616433346232356132653537613565306561393339336635353239
3366616464316663310a613536373632373734366236343966623761666530643133646336633535
39633532336136623565636437303862643230323035653266346632323637613231333539366465
6261616364313563623630613039313662656237633539346261